openapi: 3.0.3
info:
  title: Student API
  version: 1.0.0
  description: Management of students and exams
servers:
  - url: "127.0.0.1:{port}/api"
    description: Local dev
    variables:
      port:
        default: "3000"
security:
  - bearerAuth: []
paths:
  /auth/login:
    post:
      description: "Login for users and admin"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  default: niulai@gmail.com
                password:
                  type: string
                  default: Mamaaa

      responses:
        "200":
          description: User authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    format: jwt
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMiJ9.4Adcj3UFYqk
                  user:
                    $ref: "#/components/schemas/StudentSummary"
        "401":
          description: Credentials invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/students:
    get:
      description: Get students
      responses:
        "200":
          description: List of students
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudentSummary"
    post:
      description: Create users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/StudentDTO"
      responses:
        "201":
          description: Students created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Student"
        "422":
          description: Invalid data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    StudentDTO:
      type: object
      properties:
        name:
          type: string
          example: Niu Lai
        email:
          type: string
          example: niulai@gmail.com
        role:
          type: string
          enum: [ admin, student ]
          example: admin
    StudentSummary:
      type: object
      allOf:
        - $ref: "#/components/schemas/StudentDTO"
      properties:
        id:
          type: integer
          example: 67
      required: [id, name, email, role]
    Student:
      type: object
      allOf:
        - $ref: "#/components/schemas/StudentSummary"
      properties:
        password:
          type: string
          example: "password"
    Error:
      type: object
      properties:
        title:
          type: string
          example: Ressource not found
        type:
          type: string
          example: "https://example.com/not-found"
        detail:
          type: string
          example: The given path doesn't exist
        status:
          type: integer
          example: 404
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

